# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: adammoss.co.uk
email: ""
description: > # this means to ignore newlines until "baseurl:"
  This is my new blog built in Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://adammoss.co.uk" # the base hostname & protocol for your site
twitter_username: adampmoss
github_username:  adampmoss

# Build settings
markdown: kramdown