# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Adam Moss
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://adammoss.co.uk" # the base hostname & protocol for your site
secure_url: "https://adammoss.co.uk"
twitter_username: adampmoss
github_username:  adampmoss
description: "The personal blog of Adam Moss, including detailed Magento 1 & 2 posts brought to you by the Magento Fox"

# Build settings
markdown: kramdown

gems: [jekyll-sitemap']